apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-tolerations
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx-tolerations
  template:
    metadata:
      labels:
        app: nginx-tolerations
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
      tolerations:
        - key: "key1"
          operator: "Equal"
          value: "value1"
          effect: "NoSchedule"
